/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RealhomeRouteImport } from './routes/realhome'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as GalleryDetailRouteImport } from './routes/gallery/$detail'
import { Route as PostsPostsIndexRouteImport } from './routes/posts/_posts.index'
import { Route as PostsPostsPostnameRouteImport } from './routes/posts/_posts.$postname'

const RealhomeRoute = RealhomeRouteImport.update({
  id: '/realhome',
  path: '/realhome',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryDetailRoute = GalleryDetailRouteImport.update({
  id: '/gallery/$detail',
  path: '/gallery/$detail',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostsIndexRoute = PostsPostsIndexRouteImport.update({
  id: '/posts/_posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostsPostnameRoute = PostsPostsPostnameRouteImport.update({
  id: '/posts/_posts/$postname',
  path: '/posts/$postname',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/realhome': typeof RealhomeRoute
  '/gallery/$detail': typeof GalleryDetailRoute
  '/gallery': typeof GalleryIndexRoute
  '/posts/$postname': typeof PostsPostsPostnameRoute
  '/posts': typeof PostsPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/realhome': typeof RealhomeRoute
  '/gallery/$detail': typeof GalleryDetailRoute
  '/gallery': typeof GalleryIndexRoute
  '/posts/$postname': typeof PostsPostsPostnameRoute
  '/posts': typeof PostsPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/realhome': typeof RealhomeRoute
  '/gallery/$detail': typeof GalleryDetailRoute
  '/gallery/': typeof GalleryIndexRoute
  '/posts/_posts/$postname': typeof PostsPostsPostnameRoute
  '/posts/_posts/': typeof PostsPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/realhome'
    | '/gallery/$detail'
    | '/gallery'
    | '/posts/$postname'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/realhome'
    | '/gallery/$detail'
    | '/gallery'
    | '/posts/$postname'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/realhome'
    | '/gallery/$detail'
    | '/gallery/'
    | '/posts/_posts/$postname'
    | '/posts/_posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  RealhomeRoute: typeof RealhomeRoute
  GalleryDetailRoute: typeof GalleryDetailRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  PostsPostsPostnameRoute: typeof PostsPostsPostnameRoute
  PostsPostsIndexRoute: typeof PostsPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/realhome': {
      id: '/realhome'
      path: '/realhome'
      fullPath: '/realhome'
      preLoaderRoute: typeof RealhomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$detail': {
      id: '/gallery/$detail'
      path: '/gallery/$detail'
      fullPath: '/gallery/$detail'
      preLoaderRoute: typeof GalleryDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/_posts/': {
      id: '/posts/_posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/_posts/$postname': {
      id: '/posts/_posts/$postname'
      path: '/posts/$postname'
      fullPath: '/posts/$postname'
      preLoaderRoute: typeof PostsPostsPostnameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  RealhomeRoute: RealhomeRoute,
  GalleryDetailRoute: GalleryDetailRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  PostsPostsPostnameRoute: PostsPostsPostnameRoute,
  PostsPostsIndexRoute: PostsPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
